- name: Deploy Docker image to Ubuntu host
  hosts: ubuntu_host
  become: yes  # Necessary to have root privileges

  tasks:
    - name: Transfer Docker image tar file to target host
      ansible.builtin.copy:
        src: unistudio.tar
        dest: /tmp/unistudio.tar

    - name: Import Docker image on target host
      ansible.builtin.shell:
        cmd: docker import /tmp/unistudio.tar unistudio
        chdir: /tmp/

    - name: Run Docker container UniStudio
      ansible.builtin.shell:
        cmd: >
          docker run -v /etc/localtime:/etc/localtime:ro -d --net=host --restart=always -tid --name UniStudio --privileged=true unistudio /sbin/init

    - name: Transfer license.lic file to target host
      ansible.builtin.copy:
        src: license.lic
        dest: /tmp/license.lic

    - name: Remove existing license file from Docker container
      ansible.builtin.shell:
        cmd: >
          docker exec UniStudio rm -f /home/UniStudio/licenses/license.lic

    - name: Transfer license file to Docker container
      ansible.builtin.shell:
        cmd: >
          docker cp /tmp/license.lic UniStudio:/home/UniStudio/licenses/

    - name: Install npm dependencies in UniStudio/Client folder
      ansible.builtin.shell:
        cmd: >
          docker exec UniStudio /bin/bash -c "cd /home/UniStudio/client && npm install"

    - name: Install npm dependencies in UniStudio folder
      ansible.builtin.shell:
        cmd: >
          docker exec UniStudio /bin/bash -c "cd /home/UniStudio && npm install"

    - name: Run npm start development inside the Docker container
      ansible.builtin.shell:
        cmd: >
          docker exec UniStudio /bin/bash -c "cd /home/UniStudio && npm run start:dev"

    - name: Restart Docker container UniStudio
      ansible.builtin.shell:
        cmd: docker restart UniStudio
