- name: Deploy Docker image to Ubuntu host
  hosts: ubuntu_host
  become: yes  # Necessary to have root privileges

  tasks:
    - name: Transfer Docker image tar file to target host
      ansible.builtin.copy:
        src: unistudio.tar
        dest: /tmp/unistudio.tar

    - name: Import Docker image on target host
      ansible.builtin.shell: docker import /tmp/unistudio.tar unistudio
      args:
        chdir: /tmp/

    - name: Run Docker container UniStudio
      ansible.builtin.shell: >
        docker run -v /etc/localtime:/etc/localtime:ro -d --net=host --restart=always -tid --name UniStudio --privileged=true unistudio /sbin/init
